version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: Postgres
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.2
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://Postgres:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "$(openssl rand -base64 32)"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    entrypoint: ["/bin/bash", "-c"]
    command:
      - airflow db init
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/plugins:/opt/airflow/plugins

  airflow-webserver:
    image: apache/airflow:2.9.2
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://Postgres:airflow@postgres:5432/airflow
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/plugins:/opt/airflow/plugins

  airflow-scheduler:
    image: apache/airflow:2.9.2
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://Postgres:airflow@postgres:5432/airflow
    command: scheduler
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/plugins:/opt/airflow/plugins

volumes:
  postgres_data:
